import fs from "node:fs";
import path from "node:path";

/**
 * Page registry generated by `npm run sync` (scripts/sync-framer.mjs).
 * Maps each site route (decoded, e.g. "/solutions/ori-check-—-cheque-truncation-system-(cts)")
 * to its HTML document in content/pages/.
 */
type Registry = { routes: Record<string, string>; notFound: string };

const CONTENT_DIR = path.join(process.cwd(), "content");

let registry: Registry | undefined;
function getRegistry(): Registry {
  registry ??= JSON.parse(fs.readFileSync(path.join(CONTENT_DIR, "routes.json"), "utf8"));
  return registry!;
}

export function allRoutes(): string[] {
  return Object.keys(getRegistry().routes);
}

function safeDecode(s: string): string {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
}

/** Resolve catch-all segments to a route key. Segments may arrive encoded or decoded. */
export function routeFromSegments(segments: string[] | undefined): string {
  if (!segments || segments.length === 0) return "/";
  return "/" + segments.map(safeDecode).join("/");
}

export function readPage(route: string): { html: string; status: 200 | 404 } {
  const reg = getRegistry();
  const file = reg.routes[route];
  if (file) return { html: fs.readFileSync(path.join(CONTENT_DIR, "pages", file), "utf8"), status: 200 };
  return { html: fs.readFileSync(path.join(CONTENT_DIR, "pages", reg.notFound), "utf8"), status: 404 };
}
